# Allwinner H2+ quad core 256/512MB RAM SoC WiFi SPI
BOARD_NAME="WuKong Pi"
BOARD_VENDOR="wukongpi"
BOARDFAMILY="sun8i"
BOARD_MAINTAINER=""
INTRODUCED="2017"
BOOTCONFIG="wukongpi_defconfig"
MODULES_CURRENT="g_serial"
MODULES_BLACKLIST="lima sunxi_cedrus"
DEFAULT_OVERLAYS="usbhost2 usbhost3"
DEFAULT_CONSOLE="serial"
HAS_VIDEO_OUTPUT="no"
SERIALCON="ttyS0,ttyGS0"
KERNEL_TARGET="current,edge,legacy"
KERNEL_TEST_TARGET="current"
